### ISSUE TITLE
Dockerfile 리팩토링

### ISSUE THREAD

**Issue by HongYeseul** [HongYeseul/hotdeal-be#47]
## Labels
Dockerfile
``` dockerfile
LABEL description="이미지 설명"
LABEL createdAt=$BUILD_DATE
LABEL version=$GIT_COMMIT_HASH
```
docker hub 배포 스크립트
``` yaml
# ...
- ...
   - run: echo "date + '%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

  build-args: |
    BULD_DATE=${{steps.date.outputs.date}}
    GIT_COMMIT_HASH=${{steps.git.outputs.commit-hash}}
```
등과 같이 도커 파일에 나타낼 수 있다.
